/*
 * Copyright (c) 2017, [Ribose Inc](https://www.ribose.com).
 *
 * BSD-2-Clause license -- see LICENSE for details.
 */

/*
 * Frame-codec tests for the retraced control protocol
 * (TODO.supervisor/01).
 *
 * TWO IMPLEMENTATIONS, ONE ARTIFACT SET: the wire goldens under
 * share/rpc-schema/golden/ are generated by the conformance
 * suite from protocol.h's message table (the single source of
 * truth). This test asserts the C encoder produces byte-equal
 * frames for every message and that the decoder enforces the
 * receiver rules: truncation at every header offset, wrong
 * magic, oversize length, unknown-type forward-skip.
 *
 * Golden dir arrives via RETRACE_RPC_GOLDEN_DIR (set by the
 * CTest registration); without it the golden comparisons are
 * skipped (standalone runs still get the codec coverage).
 */

#include <assert.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include "protocol.h"

static int tests_run;
static int tests_pass;
static int tests_fail;

#define TEST(name) do { \
	tests_run++; \
	printf("  TEST %s ... ", #name); \
	test_##name(); \
	tests_pass++; \
	printf("OK\n"); \
} while (0)

static const struct {
	uint16_t id;
	const char *name;
	const char *file;
} g_msgs[] = {
	{ RETRACE_RPC_MSG_HELLO, "HELLO", "hello.bin" },
	{ RETRACE_RPC_MSG_HEARTBEAT, "HEARTBEAT", "heartbeat.bin" },
	{ RETRACE_RPC_MSG_POLICY_ACK, "POLICY_ACK", "policy_ack.bin" },
	{ RETRACE_RPC_MSG_EVENT, "EVENT", "event.bin" },
	{ RETRACE_RPC_MSG_RING_DATA, "RING_DATA", "ring_data.bin" },
	{ RETRACE_RPC_MSG_BYE, "BYE", "bye.bin" },
	{ RETRACE_RPC_MSG_WELCOME, "WELCOME", "welcome.bin" },
	{ RETRACE_RPC_MSG_POLICY_SET, "POLICY_SET", "policy_set.bin" },
	{ RETRACE_RPC_MSG_CMD, "CMD", "cmd.bin" },
	{ RETRACE_RPC_MSG_PING, "PING", "ping.bin" },
};

static int read_file(const char *dir, const char *file,
	uint8_t *buf, size_t cap, size_t *len)
{
	char path[512];
	FILE *f;
	size_t got;

	snprintf(path, sizeof(path), "%s/%s", dir, file);
	f = fopen(path, "rb");
	if (f == NULL)
		return -1;
	got = fread(buf, 1, cap, f);
	fclose(f);
	if (got == 0 || got >= cap)
		return -1;
	*len = got;
	return 0;
}

static void test_roundtrip_all_types(void)
{
	size_t i;

	for (i = 0; i < sizeof(g_msgs) / sizeof(g_msgs[0]); i++) {
		uint8_t out[64];
		struct retrace_rpc_frame fr;
		const char *pl = "{}";

		assert(retrace_rpc_frame_encode(out, sizeof(out),
			RETRACE_RPC_VERSION, g_msgs[i].id, pl, 2) == 0);
		assert(retrace_rpc_frame_decode(out, sizeof(out), &fr) == 0);
		assert(fr.type == g_msgs[i].id);
		assert(fr.version == RETRACE_RPC_VERSION);
		assert(fr.length == 2);
		assert(strcmp(retrace_rpc_msg_name(fr.type),
			g_msgs[i].name) == 0);
	}
}

static void test_goldens_byte_equal(void)
{
	const char *dir = getenv("RETRACE_RPC_GOLDEN_DIR");
	size_t i;

	if (dir == NULL) {
		printf("(goldens skipped: dir unset) ");
		return;
	}
	for (i = 0; i < sizeof(g_msgs) / sizeof(g_msgs[0]); i++) {
		uint8_t golden[512], encoded[512];
		size_t glen;
		struct retrace_rpc_frame fr;

		if (read_file(dir, g_msgs[i].file, golden, sizeof(golden),
			&glen) != 0) {
			printf("(golden %s unreadable) ", g_msgs[i].file);
			continue;
		}
		assert(retrace_rpc_frame_decode(golden, glen, &fr) == 0);
		assert(retrace_rpc_frame_encode(encoded, sizeof(encoded),
			fr.version, fr.type,
			golden + RETRACE_RPC_HEADER_SZ,
			fr.length) == 0);
		assert(memcmp(encoded, golden,
			RETRACE_RPC_HEADER_SZ + fr.length) == 0);
	}
}

static void test_truncation_every_offset(void)
{
	uint8_t full[RETRACE_RPC_HEADER_SZ + 2];
	struct retrace_rpc_frame fr;
	int off;

	assert(retrace_rpc_frame_encode(full, sizeof(full),
		RETRACE_RPC_VERSION, RETRACE_RPC_MSG_PING, "{}", 2) == 0);
	for (off = 0; off < RETRACE_RPC_HEADER_SZ; off++) {
		struct retrace_rpc_frame junk;

		(void)junk;
		assert(retrace_rpc_frame_decode(full, (size_t)off, &fr)
			== -2);
	}
	/* full header + partial payload: header decodes; the
	 * transport layer handles partial payloads by length
	 */
	assert(retrace_rpc_frame_decode(full, RETRACE_RPC_HEADER_SZ,
		&fr) == 0);
}

static void test_wrong_magic(void)
{
	uint8_t buf[RETRACE_RPC_HEADER_SZ];
	struct retrace_rpc_frame fr;

	assert(retrace_rpc_frame_encode(buf, sizeof(buf),
		RETRACE_RPC_VERSION, RETRACE_RPC_MSG_PING, NULL, 0) == 0);
	buf[0] = 'X';
	assert(retrace_rpc_frame_decode(buf, sizeof(buf), &fr) == -3);
}

static void test_oversize_length_rejected(void)
{
	uint8_t buf[RETRACE_RPC_HEADER_SZ];
	uint32_t hostile = RETRACE_RPC_PAYLOAD_MAX + 1;
	struct retrace_rpc_frame fr;

	assert(retrace_rpc_frame_encode(buf, sizeof(buf),
		RETRACE_RPC_VERSION, RETRACE_RPC_MSG_PING, NULL, 0) == 0);
	/* forge the length field: a receiver must refuse without
	 * allocating (plan 08's threat model)
	 */
	buf[8] = (uint8_t)(hostile & 0xff);
	buf[9] = (uint8_t)((hostile >> 8) & 0xff);
	buf[10] = (uint8_t)((hostile >> 16) & 0xff);
	buf[11] = (uint8_t)((hostile >> 24) & 0xff);
	assert(retrace_rpc_frame_decode(buf, sizeof(buf), &fr) == -4);
}

static void test_unknown_type_skips_forward(void)
{
	uint8_t buf[RETRACE_RPC_HEADER_SZ + 2];
	struct retrace_rpc_frame fr;

	assert(retrace_rpc_frame_encode(buf, sizeof(buf),
		RETRACE_RPC_VERSION, 9999, "{}", 2) == 0);
	/* forward compatibility: decode succeeds; skip by length */
	assert(retrace_rpc_frame_decode(buf, sizeof(buf), &fr) == 0);
	assert(fr.type == 9999);
	assert(fr.length == 2);
	assert(strcmp(retrace_rpc_msg_name(9999), "?") == 0);
}

static void test_encode_bounds(void)
{
	uint8_t small[4];
	static uint8_t big[RETRACE_RPC_PAYLOAD_MAX + 8];

	/* cap enforced at encode too */
	assert(retrace_rpc_frame_encode(big, sizeof(big), 1,
		RETRACE_RPC_MSG_EVENT, big,
		RETRACE_RPC_PAYLOAD_MAX + 1) == -1);
	/* insufficient output capacity */
	assert(retrace_rpc_frame_encode(small, sizeof(small), 1,
		RETRACE_RPC_MSG_PING, NULL, 0) == -2);
	/* null payload with nonzero length */
	assert(retrace_rpc_frame_encode(big, sizeof(big), 1,
		RETRACE_RPC_MSG_PING, NULL, 4) == -1);
}

int main(void)
{
	printf("rpc frame tests:\n");

	printf("  -- codec --\n");
	TEST(roundtrip_all_types);
	TEST(encode_bounds);

	printf("  -- receiver rules --\n");
	TEST(truncation_every_offset);
	TEST(wrong_magic);
	TEST(oversize_length_rejected);
	TEST(unknown_type_skips_forward);

	printf("  -- ssot pin (C == python goldens) --\n");
	TEST(goldens_byte_equal);

	printf("\nPass: %d, Fail: %d (of %d)\n",
		tests_pass, tests_fail, tests_run);
	return tests_fail == 0 ? 0 : 1;
}
