name: nix

on:
  push:
    branches:
      - main
      - 'release/**'
    paths-ignore:
      - '**.adoc'
      - '**.md'
      - '*.sh'
      - '.*'
      - 'Brewfile'
      - '_*'
      - 'doc/**'
      - '.github/workflows/*.yml'
      - '!.github/workflows/nix.yml'
      - 'ci/before_install/*'
      - 'ci/checkpatch*'
  pull_request:
    paths-ignore:
      - '**.adoc'
      - '**.md'
      - '*.sh'
      - '.*'
      - 'Brewfile'
      - '_*'
      - 'doc/**'
      - '.github/workflows/*.yml'
      - '!.github/workflows/nix.yml'
      - 'ci/before_install/*'
      - 'ci/checkpatch*'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        retrace-test: [v1, v2, v2wrapper]
    if: "!contains(github.event.head_commit.message, 'skip ci')"

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - uses: cachix/install-nix-action@v15
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - run: |
          nix build .#${{ matrix.retrace-test }} || { nix log /nix/store/*-retrace-unstable.drv ; exit 1 ; }
